# Use the official Node.js image as the base image for backend
FROM node:20.0.0-alpine AS backend

# Set the working directory for backend
WORKDIR /app/quirknotes/backend

# Copy backend package files
COPY quirknotes/backend/package*.json ./

# Install backend dependencies
RUN npm install

# Copy backend source code
COPY quirknotes/backend ./

# Install nodemon globally
RUN npm install -g nodemon

# Expose port 4000 for the backend
EXPOSE 4000

# Command to run your application
CMD ["npm", "run", "dev"]
